export const ADD_DEVICE_MARKER = "ADD_DEVICE_MARKER";
export const DELETE_DEVICE_MARKER = "DELETE_DEVICE_MARKER";
export const ADD_POLYGON_LAYER = "ADD_POLYGON_LAYER";
export const CHECKING_LAYER = "CHECKING_LAYER";
export const ENABLE_HEAT_LAYER = "ENABLE_HEAT_LAYER";
export const ENABLE_MARKER_MOVEMENT = "ENABLE_MARKER_MOVEMENT";
